name: Deploy All Odoo Modules

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    env:
      ODOO_CUSTOM_ADDONS_DIR: "C:\\Program Files\\Odoo 18.0.20250505\\server\\custom_addons"
      ODOO_SERVICE_NAME: "odoo-server-18.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop Odoo service
        run: |
          Stop-Service -Name $env:ODOO_SERVICE_NAME -Force
          Start-Sleep -Seconds 15

      - name: Copy all modules (exclude .github and .gitignore)
        run: |
          $repoRoot = (Resolve-Path "$PWD").Path
          $dst = $env:ODOO_CUSTOM_ADDONS_DIR
          
          # Copy everything except .github folder and .gitignore
          robocopy.exe "$repoRoot" "$dst" /E /XO /XD ".github" /XF ".gitignore" /R:2 /W:3 /MT:4

      - name: Start Odoo service
        run: |
          sc.exe start "$env:ODOO_SERVICE_NAME"
          Start-Sleep -Seconds 15

      - name: Done
        run: Write-Host "All modules deployed. Update Apps List in Odoo to see changes."
