name: Deploy All Odoo Modules

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    env:
      ODOO_CUSTOM_ADDONS_DIR: "C:\\Program Files\\Odoo 18.0.20250505\\server\\custom_addons"
      ODOO_SERVICE_NAME: "odoo-server-18.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy all modules (exclude .github, .gitignore, and .git)
        run: |
          $repoRoot = (Resolve-Path "$PWD").Path
          $dst = $env:ODOO_CUSTOM_ADDONS_DIR
          
          robocopy.exe "$repoRoot" "$dst" /E /XO /XD ".github" ".git" /XF ".gitignore" /R:2 /W:3 /MT:4
          
          if ($LASTEXITCODE -lt 8) { exit 0 } else { exit $LASTEXITCODE }

      - name: Upgrade All Modules in Odoo
        shell: cmd
        run: | 
          cd C:\Program Files\Odoo 18.0.20250505\server && python odoo-bin -c odoo.conf -u all --stop-after-init

      - name: Restart Odoo service
        shell: pwsh
        run: |
          Restart-Service -Name $env:ODOO_SERVICE_NAME -Force
          Start-Sleep -Seconds 15

      - name: Done
        run: Write-Host "All modules deployed and upgraded."
