name: Deploy All Odoo Modules

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    env:
      ODOO_CUSTOM_ADDONS_DIR: "C:\\Program Files\\Odoo 18.0.20250505\\server\\custom_addons"
      ODOO_SERVICE_NAME: "OdooService"
      NSSM_PATH: "C:\\Program Files\\Odoo 18.0.20250505\\nssm\\win64\\nssm.exe"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy all modules (exclude .github, .gitignore, and .git)
        run: |
          $repoRoot = (Resolve-Path "$PWD").Path
          $dst = $env:ODOO_CUSTOM_ADDONS_DIR
          
          robocopy.exe "$repoRoot" "$dst" /E /XO /XD ".github" ".git" /XF ".gitignore" /R:2 /W:3 /MT:4
          
          if ($LASTEXITCODE -lt 8) { exit 0 } else { exit $LASTEXITCODE }

      - name: Upgrade All Modules in Odoo
        shell: cmd
        run: |
          cd "C:\Program Files\Odoo 18.0.20250505\server" && ^
          "F:\Python\python.exe" odoo-bin -c odoo.conf -d odoo_deploy -u mbuzz_intern_deploy --stop-after-init

      - name: Done
        run: Write-Host "All modules deployed and upgraded."
